### ISSUE TITLE
Button Component

### ISSUE THREAD

**Issue by KatiaGhezali** [202306-NEA-DZ-FEW/StudentStore#10]
**Task title**
Reusable Button Component

**Task description**
Create a reusable button component and add a default style to it using Tailwind CSS. The button component is designed for consistent styling and usability across our project. It's a versatile component that can be used in various parts of our application.

**Subtasks**
 
- [x] Create the reusable button component.

- [x] Apply a default style to the button using Tailwind CSS classes.

- [x] Integrate tailwind merge for combining default and custom styles.

- [x] Test the button component in different parts of the project to ensure consistent styling 

**Screenshots**
![image](https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/127650953/8741ea61-933d-4fdb-8ec7-d262ca3a8d12)

**Link to the component on Figma**
[Link to the component on Figma](https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=2366-2328&mode=design&t=gFOxuV4z0rXMmNmR-4)
