### ISSUE TITLE
Create Cart page

### ISSUE THREAD

**Issue by hocine1212** [202306-NEA-DZ-FEW/StudentStore#103]
**Task title**
Create Cart page
**Task description**
Develop the Cart page for the application. This page should display the selected items, provide options for modification, and offer a smooth checkout experience.

**Subtasks**

- [x] #104 
- [x] #105 
- [x] Enhance the styling of the ProductCard components.
- [x] Implement the cartCount logic to display  the number of items in the cart.
- [x] Enable deleting functionality for users to remove items from their carts.
- [x] Set up the borrow functionality in the CartItem component
- [x] #116
- [x] Integrate emty cart svg to display it when the cart is empty
- [x] Implement Toastify notifications for user  actions in the cart page 

**Screenshots**
Put at least one screenshot here

**Link to the component on Figma**
Put the link here
