### ISSUE TITLE
Develop Cart Item Component

### ISSUE THREAD

**Issue by hocine1212** [202306-NEA-DZ-FEW/StudentStore#105]
**Task title**
Develop Cart Item Component

**Task description**
Develop a reusable Cart Item component that represents an individual item in the shopping cart. The component should display essential information about the product, such as its name, price, type and a thumbnail image. Additionally, incorporate interactive features like the ability to remove items from the cart or adjust the number of days for borrowing.

**Subtasks**

- [x] Ensure the component is reusable and easily integrated into the overall cart display.
- [x] Give special attention to creating a design that looks clean and visually pleasing.
- [x] Test the functionality of the Cart Item component thoroughly to avoid any bugs in the future and to give the user a better experience.
