### ISSUE TITLE
Products Page

### ISSUE THREAD

**Issue by Ben-Tewfik** [202306-NEA-DZ-FEW/StudentStore#110]
**Title**
Implement Products Page with Firebase Integration and Filter Component

**Task description**
Create a product page fetching product data from the Firebase Firestore Each product should be displayed in a card component, showing the product picture, name, price, category, location, and availability for sale or borrow.

**Subtasks**
- [x] #111
- [x] #114
- [x] Implement translation for the filter component (English, French, Arabic).
- [x] Add order functionality for products to show the latest products first.
- [x] Ensure responsive design for the products page.
