### ISSUE TITLE
ProductsContainer Component

### ISSUE THREAD

**Issue by Ben-Tewfik** [202306-NEA-DZ-FEW/StudentStore#111]
**Title**
ProductsContainer Component
**Description**:
Create a ProductsContainer component that will display the filter and ProductsList component. The ProductsList component will be a container for productCard. Each product card will show details such as picture, name, price, category, and availability for sale or borrow.

**Subtasks:**
 
- [x] Create the ProductsContainer component.

- [x] Create the ProductsList component.

- [x] Pass product data to the ProductList component.
