### ISSUE TITLE
Filter Products component

### ISSUE THREAD

**Issue by Ben-Tewfik** [202306-NEA-DZ-FEW/StudentStore#114]
**Title**
Create a Filter component for the products page.

**Description**
Create a filter component to filter products based on categories, price range, and Type borrow or sale.

**Subtasks**

- [x]  Create the basic structure of the Filter component.

- [x]  Implement a price range filter that allows users to specify a minimum and maximum price.

- [x]  Implement a type filter that allows users to choose between borrowing or buying/selling products.

- [x]  Implement a category filter that allows users to select one or multiple categories.

- [x]  Implement a Condition filter that allows users to select one or multiple conditions of the product like new good poor.

- [x] Translate filter component into french and Arabic

- [x] Style the filter component and test the responsiveness into multiple screens.
