### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by KatiaGhezali** [202306-NEA-DZ-FEW/StudentStore#12]
**Task title**
Footer Responsiveness and Design Styling

**Task description**
The footer component of our project requires improvements in terms of responsiveness and design styling to ensure it displays correctly and looks visually appealing on different devices and screen sizes.

**Subtasks**

- [x] Ensure the footer is responsive for mobile devices.

- [x]  Adjust font size and spacing for better readability.

- [x] Apply brand colors and styling to the footer.

- [x] Add test for the footer component.

- [x] Implement the links for a swift navigation between the pages.

**Screenshots**
Put at least one screenshot here
Desktop :
<img width="607" alt="desktop" src="https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/137809274/4eaee444-9333-4e57-87de-c90342e00c7d">

Tablet :
<img width="302" alt="tablet" src="https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/137809274/5c48fa59-c8bb-4c2b-a9ae-0faade795781">

Mobile :
<img width="176" alt="mobile" src="https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/137809274/f6d44d5f-7275-4294-a53a-b7a3c5157362">

**Link to the component on Figma**
Put the link here
Desk top version:
https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=123-14088&mode=design&t=A1Bfa7VVZuoc9XKV-4
Tablet version :
https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=201-14740&mode=design&t=A1Bfa7VVZuoc9XKV-4
Mobile version :
https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=213-16001&mode=design&t=A1Bfa7VVZuoc9XKV-4
