### ISSUE TITLE
Add Arabic and French Translations on the Listing Page

### ISSUE THREAD

**Issue by hocine1212** [202306-NEA-DZ-FEW/StudentStore#128]
**Task title**
Add Arabic and French Translations on the Listing Page

**Task description**
Enhance the Listing page by adding translations in Arabic and French. This improvement aims to make the platform more user-friendly for speakers of these languages. Translations will cover essential elements like the form inputs , the buttons and and toastify notifications

**Subtasks**

- [x] Translated form inputs into Arabic and French.
- [x] Translated buttons into Arabic and French.
- [x]  Added translations for toastify notifications in Arabic and French.
