### ISSUE TITLE
Implement Arabic and French Translations for the Cart Page

### ISSUE THREAD

**Issue by hocine1212** [202306-NEA-DZ-FEW/StudentStore#133]
**Task title**
Implement Arabic and French Translations for the Cart Page

**Task description**
Implemented language translation features for the Cart Page to enhance accessibility for Arabic and French-speaking users.The updates include the translation of essential elements such as CartItem and OrderSummary components  and toast notifications.

**Subtasks**
- [x]  Translated CartItem component
- [x]  Translated OrderSummary component
- [x]  Added translations for buttons
- [x]  Implemented translations for Toastify notifications"
