### ISSUE TITLE
Language Translation dropdown

### ISSUE THREAD

**Issue by KatiaGhezali** [202306-NEA-DZ-FEW/StudentStore#15]
**Task title**
 Language Translation dropdown

**Task description**
Create a multilingual support component. This component will consist of a language selection button in the website's navbar, offering three language options: English (default), Arabic, and French.
**Subtasks**

- [x]  Design and develop a language selection button, integrating it into the website's navbar.

- [x] Ensure that English is set as the default language for all pages.

- [x]  Implement the ability for users to click on "Arabic" and have the current page translated into Arabic.

- [x] Implement the ability for users to click on "French" and have the current page translated into French.

- [x] Enable the user's selected language to persist across different pages and sessions.

- [x] test the multilingual support component across various pages to ensure seamless translation.

**Screenshots**
![image](https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/127650953/4781b666-761e-4da0-8f9f-a638a65349fa)

**Link to the component on Figma**
[Link to the component on Figma](https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=2583-14780&mode=design&t=ybUZEUBWbOju5GLf-4)
