### ISSUE TITLE
Add "Transact" button to the Navbar and Side bar

### ISSUE THREAD

**Issue by MouniaBelkheir** [202306-NEA-DZ-FEW/StudentStore#152]
**Task title**

Add "Add" button to the Navbar and Side bar

**Task description**
This task involves integrating a "Add" button into both the navbar and the sidebar of our website. The button should be positioned for easy user access. Ensure that the button is functional and redirects users to the appropriate page when clicked.

**Subtasks**

- [x] Integrate the button into the navbar.
- [x] Integrate the button into the sidebar.
- [x] Add Arabic and French translation to the json files
- [x] Test the button to ensure proper functionality.
- [x] Ensure design consistency with the rest of the site.
- [x] Test in different screen sizes.
