### ISSUE TITLE
UnderBar

### ISSUE THREAD

**Issue by KatiaGhezali** [202306-NEA-DZ-FEW/StudentStore#16]
**Task title**
UnderBar component

**Task description**
Create an underbar component to use in the website's navbar to display product categories. This underbar should provide easy navigation for users to access different product categories available on the website.

**Subtasks**

- [x] Implement the Underbar 

- [x] Populate the underbar with the list of product categories. ( All categories, Electronics, Books, Gaming, Clothes, Food, Transportation, Furniture)

- [x] Add styling and Ensure the underbar matches the website's overall design.

**Screenshots**
![image](https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/127650953/8fb72bb4-2669-4926-90ad-4622c4f91db0)

**Link to the component on Figma**
[Figma Link](https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=2398-2334&mode=design&t=bT7xpes4umdKWqhN-4)
