### ISSUE TITLE
HeroSection

### ISSUE THREAD

**Issue by KatiaGhezali** [202306-NEA-DZ-FEW/StudentStore#17]
**Task title**
Create Hero Section component

**Task description**
The HeroSection on the Student Store website needs improvements and refinements. It should effectively capture the attention of visitors and provide an engaging introduction to the website.

**Subtasks**

- [x]  Enhance the visual design of the HeroSection.
- [x]  Add eye-catching images and graphics.
- [x]  Ensure responsive design for various screen sizes.

**Screenshots**
![image](https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/127650953/4d319b6c-7ae4-459a-a8b4-dfb499a29962)

**Link to the component on Figma**
[Figma Link](https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=3211-5589&mode=design&t=zaKYqzxLrVNiYnhT-4)
