### ISSUE TITLE
Onboarding 

### ISSUE THREAD

**Issue by samiba6** [202306-NEA-DZ-FEW/StudentStore#24]
**Task title**
Onboarding page design 
**Task description**
  designing the Onboarding  page using Figma.
**Subtasks**

- [x] - Design the onboarding page.
- [x] - Design the illustrations.
- [x] Design version for Tablets and mobiles 

**Screenshots**
<img width="343" alt="image" src="https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/51706925/094081e2-120b-407c-a1c5-59aeaf0f308c">

**Link to the component on Figma**
[Figma Link](https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=2339-2317&mode=design&t=DIohLE31LbH9gvHx-0)
