### ISSUE TITLE
Firebase authentication confugartion

### ISSUE THREAD

**Issue by Ben-Tewfik** [202306-NEA-DZ-FEW/StudentStore#29]
**Task title**
Configure Firebase Authentication with Email, Gmail, Facebook

**Task description**
In this task, we aim to set up Firebase Authentication to allow users to sign in using various methods, including email, Gmail, and Facebook.
**Subtasks**

- [x] Implement email and password authentication using Firebase. 

- [x] Configure Gmail authentication using Firebase.

- [x] Set up Facebook authentication with Firebase.

- [x] Set up Twitter authentication with Firebase

- [x] Test the authentication methods to ensure they work correctly.

**Screenshots**
![image](https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/127650953/28e1ab0f-4f34-4196-9616-ff2ba14c7b60)

**Comment by Ben-Tewfik** [comment]
Issue successfully completed! All authentication methods have been implemented and tested on the local host.
We are now in the process of finalizing the pages and components related to these authentication methods. Once the pages and components are ready, we will conduct additional testing for Facebook and Twitter authentication on Vercel to ensure their functionality in a production environment.
