### ISSUE TITLE
Map.

### ISSUE THREAD

**Issue by KatiaGhezali** [202306-NEA-DZ-FEW/StudentStore#33]
### **Task title**
Create a Map Component

### **Task description**
Create a map component that interacts with Firebase collections (userinfo and position). Fetch the city from the userinfo collection, find the corresponding city in the position collection, and display the location on the map using the retrieved coordinates.

### **Subtasks**

- [x] Fetch city from the userinfo collection in Firebase.

- [x] Compare the city with cities in the position collection to find matching coordinates.

- [x] Display the location on the map.

- [x] Handle window issues and ensure the map displays correctly without any errors.

- [ ]  Handle any problems that might occur when testing the component #77 

### **Screenshots**
![image](https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/74726931/52a2e8a7-3be4-4ea8-90e4-ec3fb2d513b1)

### **Link to the component on Figma**
[The map component](https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=120-11066&mode=design&t=MZCcgOsJZPOHG4hF-4)
