### ISSUE TITLE
Listing page

### ISSUE THREAD

**Issue by KatiaGhezali** [202306-NEA-DZ-FEW/StudentStore#38]
**Task title**
Create Listing Page
**Task description**
Implement a page where users can list products for sale or borrow by filling in the necessary information and uploading images. The data will be sent to Firebase Firestore, and the images will be stored in Firebase Storage.

**Subtasks**

- [x] Create the Listing Page
- [x] Create form inputs for the following fields:
- Type (Product or Service)
-  Category
-  Product Title
-  Description
-  Location
-  Price
-  Image Upload (Up to 4 images)
- [x] #45

- [x] Implement Form Validation by
-  Add validation to ensure that required fields are filled out.
-   Limit image uploads to a maximum of 4 images.
- [x]  Set up Firebase Firestore integration for storing the product or service information.
- [x] Implement image storage in Firebase Storage for the uploaded images.
- [x]  Create a function to submit the data to Firestore when the user clicks the "List" button.
- [x] After successful submission, clear the form to allow users to list another product.
- [x] #46

**Screenshots**
For Desktops:
![image](https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/122048230/da8b4157-0529-4f5f-ab79-96e74e8af055)
For Tablets :
![image](https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/122048230/39f06ac3-568b-413f-bd82-6ac4337e14ab)
For Mobiles:
![image](https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/122048230/8f48e6ad-ac38-4ed6-9703-619a4ff44a90)

**Link to the Page design on Figma**
[Large screens](https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=125-31416&mode=design&t=zdacYJmX7UEHhJD3-4=)
[Medium screens](https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=125-31559&mode=design&t=zdacYJmX7UEHhJD3-4 )
[Small screens](https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=125-31814&mode=design&t=zdacYJmX7UEHhJD3-4)
