### ISSUE TITLE
Sign Up Page

### ISSUE THREAD

**Issue by Ben-Tewfik** [202306-NEA-DZ-FEW/StudentStore#41]
**Task title**
Design and Implement Signup Page

**Task description**
Create a Signup Page with Firebase as a backend. The page contains :

1. A form for signing up with email. The form includes the following :

- Name input 
- Surname input 
- Email Address input 
- School Name input 
- Password input 
- Confirm Password input 
- Sign Up button

2. Optional Social Sign-Up Options:

- Sign up with Google button
- Sign up with Facebook button
- Sign up with Twitter button

3. Sign In button:
 It is a link that should lead to the Sign In page if the user already has an account.
 

**Subtasks**

- [x] Design the Signup Page UI
- [x] #48
- [x] Implement form validation for password and email
- [x] #42
- [x] #50
- [x] Style and Test the page across various devices and browsers

**Screenshots**
for Desktop:
![image](https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/127650953/435b47c8-8d47-46fe-8059-79337f790c82)
for Tablet :
![image](https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/127650953/0c39f943-2722-4184-acf8-7e83bd03ba11)
for mobile:
![image](https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/127650953/b8b65c71-715e-435c-b53b-3226815c3d11)

**Link to the component on Figma**
[Sign Up page Figma Link](https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=2453-10600&mode=design&t=e4PXEex06i9z6uZS-4)
