### ISSUE TITLE
Splash page

### ISSUE THREAD

**Issue by samiba6** [202306-NEA-DZ-FEW/StudentStore#52]
**Task title**
Splash page
**Task description**

**Subtasks**

- [x]  Create Animated Component

Responsiveness
- [x] Splash page Desktop
- [x] Splash page Tablets
- [x] Splash smartphones 

**Screenshots**
<img width="450" alt="image" src="https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/51706925/65496d9a-7da8-455c-800d-c92222db802d">

**Link to the component on Figma**
[Splash page here !](https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=2465-5867&mode=design&t=lxNGtjMghSNlFbE5-4)
