### ISSUE TITLE
Sign In Page

### ISSUE THREAD

**Issue by Ben-Tewfik** [202306-NEA-DZ-FEW/StudentStore#55]
**Task title**
Design and Implement Signin Page

**Task description**
Create a Signin Page with Firebase as a backend. The page contains :

1. A form for signing in with email and password. The form includes the following :

- Email Address input
- Password input
- Sign In button
- Forgot Password button

2. Optional Social Sign-In Options:

- Sign in with Google button
- Sign in with Facebook button
- Sign in with Twitter button

3. Sign up button: It is a link that should lead to the Signup page if the user does not have an account.

**Subtasks**

- [x] Design the Signup Page UI
- [x] #56
- [x] #61
- [x]  reuse the socials buttons from the signup page  #42
- [x] #62
- [x]  Style and Test the page across various devices and browsers

**Screenshots**
for Desktop:
![image](https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/127650953/399c4013-316b-452b-98bb-7140d901dbd1)
for Tablet :
![image](https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/127650953/8f6a2738-7e8c-411b-a505-7efd7f205b70)
for mobile:
![image](https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/127650953/aaeaa2f2-2ebd-49d0-b2eb-1757acd57335)

**Link to the component on Figma**
[Sign Up page Figma Link](https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=2453-10600&mode=design&t=e4PXEex06i9z6uZS-4)
