### ISSUE TITLE
Design Splash page 

### ISSUE THREAD

**Issue by samiba6** [202306-NEA-DZ-FEW/StudentStore#57]
**Task title**
Design Splash page 
**Task description**
Design Splash (welcoming) page for Desktop, Tablets, smartphones
**Subtasks**

- [x] Design Splash page for Desktop, Tablets, smartphones.
- [x] Design Splash page for Tablets.
- [x] Design Splash page for smartphones.

**Screenshots**
![image](https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/51706925/30755534-5ea1-4fc4-970a-63df66eb956d)
**Link to the component on Figma**
[Link to splash/onboarding pages](https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=2453-10600&mode=design&t=XfcaUvURSjOhu3Kv-4)
