### ISSUE TITLE
Reset Password Page

### ISSUE THREAD

**Issue by Ben-Tewfik** [202306-NEA-DZ-FEW/StudentStore#61]
**Task Title**
Create a reset password page

**Task Description**
Create the structure of the reset password form,  It will include an input field and a button.

**Subtasks**

- [x] Design the Reset Password Page UI
- [x] Create the structure of the page
- [x] #30 
- [x]  Style and Test the page across various devices and browsers
**Screenshots**
for Desktop:
![image](https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/127650953/444a6fe1-5ce3-47a6-b0d3-44404ab3103f)

for Tablet :
![image](https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/127650953/4642c941-a649-4f4e-93e8-964cb0a2ac61)

for mobile:
![image](https://github.com/202306-NEA-DZ-FEW/StudentStore/assets/127650953/c6f78793-f7b4-4dc5-9e5f-b3b30da5c1db)

**Link to the component on Figma**
[Sign Up page Figma Link](https://www.figma.com/file/1ivLCv0Ardin5Ii83yuQp5/Student-Store-(Capstone)?type=design&node-id=2453-10600&mode=design&t=e4PXEex06i9z6uZS-4)
