### ISSUE TITLE
Translate Donations Page

### ISSUE THREAD

**Issue by hocine1212** [202306-NEA-DZ-FEW/StudentStore#71]
**Task title**
Translate Donations Page

**Task description**
Add translation support to the existing Donation Page to make it available in multiple languages, including English, Arabic, and French.

**Subtasks**
- [x]  Create language-specific translation files for English, Arabic, and French.
- [x]  Add Support for multiple languages in user interface elements on the Donations Page, covering the 'Why Donating Matters' section and Pricing Card Text.
- [x]  Test the Donations Page to confirm that it displays in the selected language based on user preferences.
