### ISSUE TITLE
Enhance Listing Page

### ISSUE THREAD

**Issue by hocine1212** [202306-NEA-DZ-FEW/StudentStore#75]
**Task title**
Enhance Listing Page

**Task description**
The goal of this task is to improve the Listing Page by introducing additional input fields to enhance the quality of product listings. These new fields will include options for specifying the product's location (city ) and its condition. Plus, we're making listing  process  super smooth by bringing in the Uploading component.

**Subtasks**

- [x]  Implement input fields for specifying the product's location(city).
- [x]  Add an input field for describing the product's condition.
- [x]  Ensure that the input fields are designed with a user-friendly interface and appropriate styling.
- [x]  Bring the Uploading component into action for a smoother listing process  (#83 )
