### ISSUE TITLE
Project-Structure

### ISSUE THREAD

**Issue by KatiaGhezali** [202306-NEA-DZ-FEW/StudentStore#8]
**Task title**
Project Structure

**Task description**
Create the necessary files to set up an environment where it is easy to work

**Subtasks**
- [x] create a components folder

     - [x] Create a navigation bar component folder
         - [x] Create a button component folder
         - [x] Create a search bar component folder
         - [x] Create an under-bar component folder
         - [x] Create a language translation component folder
         - [x] Create a profile component folder

     - [x] Create a footer component
     - [x] Create a hero section component
    - [x] Create a featured universities component
    - [x] Create a product card component folder
    - [x] Create a testimonials section component folder
