### ISSUE TITLE
Create Uploading component

### ISSUE THREAD

**Issue by hocine1212** [202306-NEA-DZ-FEW/StudentStore#83]
**Task title**
Create Uploading component.

**Task description**
Integrate Uploading Component into the listing page to provide a visually appealing and user-friendly experience during the image uploading process. The component should appear when the user clicks "List" and disappear once the listing is complete.

**Subtasks**
Put the subtasks here if any (optional)

**Screenshots**

- [x] Create a state to manage the visibility of the upload component.
- [x] Show the upload component when the user clicks the "List" button.
- [x] Hide the upload component when the listing is successfully added or if there is an error.
- [x] Ensure smooth transitions for the appearance and disappearance of the upload component.
