### ISSUE TITLE
Ajust Searchbar styling and fix layout issues

### ISSUE THREAD

**Issue by hocine1212** [202306-NEA-DZ-FEW/StudentStore#91]
**Task title**
Ajust Searchbar styling and fix layout issues

**Task description**
The Searchbar styling is currently not matching the Navbar design. To address this issue, I propose modifying the Searchbar styling to align with the Navbar design. Additionally, the task involves  fixing the navbar responsiveness in medium screen sizes . Lastly, i aim to wrap all pages using the layout to have a consistent structure with a navbar and a footer across the website.

**Subtasks**

- [x] Updated the SearchBar styling to match Navbar design.
- [x] Enhance Navbar Responsiveness for Different Screen Sizes.
- [x] Implement a layout wrapper for all pages, including a common navbar and footer.
